import "./globals.css";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "School Canteen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-gray-900">
        <Navbar />
        <main className="pt-4">{children}</main>
      </body>
    </html>
  );
}
